// Audit tests for Crystal::ReduceRaypath orbit invariant property.
//
// Background (scratchpad/scrum-filter-architecture-refactor/explore-reduce-raypath-audit/):
//   Task #209 fixed sigma_a≠0 + P+D canonicalization but covered only one case.
//   This audit systematically verifies orbit invariant across 5 dimensions:
//     H1: prism + kSymP + sigma_a≠0
//     H2: kSymB (basal 1↔2 + pyramid upper↔lower)
//     H3: pyramid crystal (双位编码 face_id 13..18/23..28)
//     H4: multi-segment (rp.size up to kMaxHits=8)
//     H5: mixed crystal type config
//     H6: low-symmetry shapes (non-uniform face distances, unequal cones) — the reduction must
//         use only the symmetry elements the crystal's shape really has
//
// Orbit invariant property:
//   For any raypath rp and any g in the symmetry group G generated by the active
//   symmetries, ReduceRaypath(rp) == ReduceRaypath(g·rp). The orbit {g·rp : g ∈ G}
//   is enumerated via Crystal::ExpandRaypath. Every orbit member must reduce to
//   the same canonical representative.
//
// On failure: this audit produces a minimal repro (failing orbit member + the two
// distinct canonicals) — the same pattern as #209's fix scope.

#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <random>
#include <set>
#include <string>
#include <vector>

#include "config/filter_config.hpp"
#include "core/crystal.hpp"
#include "core/def.hpp"

namespace lumice {
namespace {

// Format a raypath vector for diagnostic output.
std::string FormatRaypath(const std::vector<IdType>& rp) {
  std::string s = "{";
  for (size_t i = 0; i < rp.size(); i++) {
    if (i > 0) {
      s += ", ";
    }
    s += std::to_string(rp[i]);
  }
  s += "}";
  return s;
}

// Verify the orbit invariant for one (crystal, symmetry, sigma_a, d_applicable, rp_seed) tuple.
// Returns ::testing::AssertionResult so EXPECT_TRUE prints the failing detail.
::testing::AssertionResult VerifyOrbitInvariant(const Crystal& crystal, uint8_t symmetry, int sigma_a,
                                                bool d_applicable, const std::vector<IdType>& rp_seed) {
  auto canonical_seed = crystal.ReduceRaypath(rp_seed, symmetry, sigma_a, d_applicable, true, true);
  auto orbit = crystal.ExpandRaypath(rp_seed, symmetry, sigma_a, d_applicable, true, true);
  if (orbit.empty()) {
    return ::testing::AssertionFailure() << "ExpandRaypath returned empty orbit for seed " << FormatRaypath(rp_seed);
  }
  for (const auto& member : orbit) {
    auto canonical_member = crystal.ReduceRaypath(member, symmetry, sigma_a, d_applicable, true, true);
    if (canonical_member != canonical_seed) {
      return ::testing::AssertionFailure()
             << "Orbit invariant broken:" << "\n  seed:               " << FormatRaypath(rp_seed)
             << "\n  seed canonical:     " << FormatRaypath(canonical_seed)
             << "\n  orbit member:       " << FormatRaypath(member)
             << "\n  member canonical:   " << FormatRaypath(canonical_member)
             << "\n  symmetry=" << static_cast<int>(symmetry) << " sigma_a=" << sigma_a
             << " d_applicable=" << d_applicable;
    }
  }
  return ::testing::AssertionSuccess();
}

}  // namespace

// ============================================================================
// H2: kSymB orbit invariant
// ============================================================================
// kSymB encodes basal 1↔2 + pyramid upper [13..18]↔lower [23..28]; prism faces unchanged.
// Coverage: B-only / P+B / D+B / P+D+B across prism and pyramid crystals.

TEST(H2_KSymB_Audit, BasalReflect_Prism) {
  // Prism with basal+prism raypath: B flips basal 1↔2, prism face unchanged.
  Crystal prism = Crystal::CreatePrism(1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymB, 0, false, { 1, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymB, 0, false, { 2, 7 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymB, 0, false, { 1, 3, 2 }));
}

TEST(H2_KSymB_Audit, BasalAndPyramidReflect_Pyramid) {
  // Pyramid with basal+upper raypath: B flips basal 1↔2 AND pyramid 13↔23.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymB, 0, false, { 1, 13 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymB, 0, false, { 13, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymB, 0, false, { 23, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymB, 0, false, { 1, 13, 5, 23 }));
}

TEST(H2_KSymPB_Audit, PrismRaypath_Prism) {
  // P+B on prism: P rotates prism pri, B flips basal — independent symmetries.
  Crystal prism = Crystal::CreatePrism(1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, false, { 3, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, false, { 1, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, false, { 1, 3, 5 }));
}

TEST(H2_KSymPB_Audit, MixedRaypath_Pyramid) {
  // P+B on pyramid with basal+upper+prism: full interaction.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, false, { 1, 13 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, false, { 13, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, false, { 1, 13, 5 }));
}

TEST(H2_KSymDB_Audit, PrismRaypath_Prism) {
  // D+B on prism (sigma_a=0): D rotates prism pri via reflection, B flips basal.
  Crystal prism = Crystal::CreatePrism(1.0f);
  uint8_t sym = FilterConfig::kSymD | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 3, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 1, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 1, 3, 7 }));
}

TEST(H2_KSymDB_Audit, MixedRaypath_Pyramid) {
  // D+B on pyramid: D reflects pri on prism + pyramid (same pri arithmetic),
  // B flips basal + upper↔lower pyramid. Most complex single-pair interaction.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  uint8_t sym = FilterConfig::kSymD | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 13, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13, 5, 23 }));
}

TEST(H2_KSymPDB_Audit, FullSymmetry_Prism) {
  // P+D+B on prism: full hexagonal symmetry group.
  Crystal prism = Crystal::CreatePrism(1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymD | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 3, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 1, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 5, true, { 3, 5 }));  // non-zero sigma_a
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 1, 3, 5, 7 }));
}

TEST(H2_KSymPDB_Audit, FullSymmetry_Pyramid) {
  // P+D+B on pyramid: full symmetry group including upper↔lower pyramid swap.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymD | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 13, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13, 5, 23 }));
}

// ============================================================================
// H1: prism + kSymP + sigma_a ≠ 0 orbit invariant
// ============================================================================
// sigma_a only enters the D block; with kSymP alone, sigma_a should be ignored.
// Test guards against accidental sigma_a leakage from external callers.

TEST(H1_KSymP_SigmaA_Audit, SigmaA_Ignored_Prism) {
  Crystal prism = Crystal::CreatePrism(1.0f);
  // Same orbit invariant should hold across sigma_a ∈ {0, 1, 3, 5} and d_applicable both flags.
  for (int sigma_a : { 0, 1, 3, 5 }) {
    for (bool d_applicable : { false, true }) {
      EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymP, sigma_a, d_applicable, { 3, 5 }))
          << "sigma_a=" << sigma_a << " d_applicable=" << d_applicable;
      EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymP, sigma_a, d_applicable, { 1, 5, 7 }))
          << "sigma_a=" << sigma_a << " d_applicable=" << d_applicable;
    }
  }
}

TEST(H1_KSymP_SigmaA_Audit, SigmaA_Ignored_Pyramid) {
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  for (int sigma_a : { 0, 1, 3, 5 }) {
    for (bool d_applicable : { false, true }) {
      EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, sigma_a, d_applicable, { 13, 5 }))
          << "sigma_a=" << sigma_a << " d_applicable=" << d_applicable;
      EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, sigma_a, d_applicable, { 1, 13, 5 }))
          << "sigma_a=" << sigma_a << " d_applicable=" << d_applicable;
    }
  }
}

// Cross-check: sigma_a affects only D block, so canonical for kSymP must be sigma_a-independent.
TEST(H1_KSymP_SigmaA_Audit, Canonical_Independent_of_SigmaA) {
  Crystal prism = Crystal::CreatePrism(1.0f);
  std::vector<IdType> rp = { 3, 5 };
  auto baseline = prism.ReduceRaypath(rp, FilterConfig::kSymP, 0, false, true, true);
  for (int sigma_a : { 0, 1, 3, 5 }) {
    for (bool d_applicable : { false, true }) {
      auto canonical = prism.ReduceRaypath(rp, FilterConfig::kSymP, sigma_a, d_applicable, true, true);
      EXPECT_EQ(canonical, baseline) << "sigma_a=" << sigma_a << " d_applicable=" << d_applicable;
    }
  }
}

// ============================================================================
// H3: pyramid crystal (双位编码 face_id 13..18 / 23..28) orbit invariant
// ============================================================================
// Pyramid encoding: pyr * 10 + pri where pyr ∈ {0=prism, 1=upper, 2=lower}.
// Key audit dimensions:
//   - pyr part preservation through P shift (only pri rotated)
//   - pyr part preservation through D reflect (only pri reflected)
//   - first_pri detection on multi-pyramid raypath (which segment sets first_pri?)
//   - pyramid-only raypath orbit (no prism faces, no basal)

TEST(H3_PyramidEncoding_Audit, UpperPyramidOnly_P) {
  // raypath of pure upper pyramid faces; verifies P shift preserves pyr=1.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 13, 15 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 14, 16, 18 }));
}

TEST(H3_PyramidEncoding_Audit, LowerPyramidOnly_P) {
  // raypath of pure lower pyramid faces; verifies P shift preserves pyr=2.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 23, 25 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 24, 26, 28 }));
}

TEST(H3_PyramidEncoding_Audit, MixedUpperLowerPyramid_P) {
  // upper + lower pyramid mixed; first_pri is from first non-basal segment.
  // For {13, 23}: first_pri = 3 (from 13). Then face 23: pri = 23 % 10 = 3,
  // shift by 6-3=3 → (3+3)%6+3 = 0+3 = 3. Wait, let me recompute.
  // first_pri logic: first non-basal segment's pri = x % 10. For face 13: pri = 13 % 10 = 3.
  // For face 23: pri = 23 % 10 = 3. shift: (3 + 6 - 3) % 6 + 3 = 6 % 6 + 3 = 3. So 23 → 2*10+3 = 23 ✓
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 13, 23 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 18, 28, 14 }));
}

TEST(H3_PyramidEncoding_Audit, PyramidWithPrism_P) {
  // Mixed pyramid + prism; first_pri determined by leftmost prism-or-pyramid face.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 13, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 5, 13 }));  // order matters for first_pri
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 1, 13, 5, 23 }));
}

TEST(H3_PyramidEncoding_Audit, PyramidOnly_D) {
  // Pyramid-only raypath under D; pyr part should pass through D reflection unchanged.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymD, 0, true, { 13, 15 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymD, 0, true, { 23, 25 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymD, 0, true, { 13, 23 }));
  // sigma_a ≠ 0 with D
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymD, 3, true, { 13, 15 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymD, 5, true, { 18, 28 }));
}

TEST(H3_PyramidEncoding_Audit, PyramidOnly_PD) {
  // P+D on pure pyramid raypath; verifies combined pyr-preservation + pri-correctness.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymD;
  for (int sigma_a : { 0, 1, 3, 5 }) {
    EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, sigma_a, true, { 13, 15 })) << "sigma_a=" << sigma_a;
    EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, sigma_a, true, { 23, 25 })) << "sigma_a=" << sigma_a;
    EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, sigma_a, true, { 13, 23 })) << "sigma_a=" << sigma_a;
    EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, sigma_a, true, { 18, 5, 28 })) << "sigma_a=" << sigma_a;
  }
}

// ============================================================================
// H4: multi-segment (rp.size ∈ [3, kMaxHits=8]) orbit invariant
// ============================================================================
// Key risk: PCanonicalShift's `first_pri` is determined by the first non-basal
// segment and applied uniformly to all remaining segments. If implementation
// accidentally reset first_pri per-segment or mixed coordinate, multi-segment
// raypaths would break orbit invariant.

TEST(H4_MultiSegment_Audit, LongPrismOnly_PD) {
  Crystal prism = Crystal::CreatePrism(1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymD;
  // 5-segment all prism, mixed pri values
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 3, 5, 7, 4, 8 }));
  // 6-segment with repeats (raypath that loops through prism faces)
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 3, 5, 3, 5, 3, 5 }));
  // 8-segment (kMaxHits) all prism
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 3, 4, 5, 6, 7, 8, 3, 4 }));
  // 7-segment with sigma_a ≠ 0
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 5, true, { 3, 4, 5, 6, 7, 8, 3 }));
}

TEST(H4_MultiSegment_Audit, LongMixed_FullSymmetry_Pyramid) {
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymD | FilterConfig::kSymB;
  // 5-segment mixing basal + prism + pyramid (upper + lower)
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13, 5, 23, 7 }));
  // 6-segment heavy pyramid
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 13, 14, 15, 23, 24, 25 }));
  // 8-segment (kMaxHits) max stress
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13, 5, 23, 7, 14, 2, 24 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 5, true, { 1, 13, 5, 23, 7, 14, 2, 24 }));
}

// ============================================================================
// H5: mixed crystal type config — per-crystal canonical isolation
// ============================================================================
// FilterSpec in C2 holds per-crystal canonical. Crystal is a value type with
// per-instance fn_map_/fn_period_/poly_face_data, so isolation is by design.
// This sanity test verifies no sneaky shared state exists.

TEST(H5_MixedCrystal_Audit, PrismPyramidIsolation) {
  Crystal prism = Crystal::CreatePrism(1.0f);
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  std::vector<IdType> rp = { 3, 5 };

  // Same raypath, same symmetry, different crystals — both should be valid canonical
  // representatives of their respective orbits. They may equal each other (because
  // {3,5} prism orbit overlaps the pyramid {3,5} prism-only orbit), but the audit
  // verifies neither crystal pollutes the other.
  auto canonical_prism_alone = prism.ReduceRaypath(rp, FilterConfig::kSymP, 0, false, true, true);
  auto canonical_pyramid_alone = pyramid.ReduceRaypath(rp, FilterConfig::kSymP, 0, false, true, true);

  // Compute interleaved to detect any shared state.
  auto canonical_prism_2 = prism.ReduceRaypath(rp, FilterConfig::kSymP, 0, false, true, true);
  auto canonical_pyramid_2 = pyramid.ReduceRaypath(rp, FilterConfig::kSymP, 0, false, true, true);
  auto canonical_prism_3 = prism.ReduceRaypath(rp, FilterConfig::kSymP, 0, false, true, true);

  // Same crystal must give identical canonical.
  EXPECT_EQ(canonical_prism_alone, canonical_prism_2);
  EXPECT_EQ(canonical_prism_alone, canonical_prism_3);
  EXPECT_EQ(canonical_pyramid_alone, canonical_pyramid_2);

  // Each crystal's orbit invariant still holds.
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymP, 0, false, rp));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, rp));
}

TEST(H5_MixedCrystal_Audit, PyramidFacesRejectedByPrism) {
  // pyramid face (e.g., 13) on a prism crystal is technically not a valid face,
  // but ReduceRaypath should still produce some deterministic result without crash.
  Crystal prism = Crystal::CreatePrism(1.0f);
  std::vector<IdType> rp_pyramid_face = { 13, 5 };
  auto canonical = prism.ReduceRaypath(rp_pyramid_face, FilterConfig::kSymP, 0, false, true, true);
  // The result is implementation-defined; we just check the call doesn't crash and
  // is deterministic across calls.
  auto canonical_again = prism.ReduceRaypath(rp_pyramid_face, FilterConfig::kSymP, 0, false, true, true);
  EXPECT_EQ(canonical, canonical_again);
}

TEST(H4_MultiSegment_Audit, FirstPriProvenance_PD) {
  // Test that first_pri is correctly determined and applied uniformly.
  // raypath {3, 5, 7}: first_pri = 3 (from face 3). All shifts: face 5 → (5+6-3)%6+3 = 5,
  // face 7 → (7+6-3)%6+3 = 7. Canonical: {3, 5, 7} (already canonical, first_pri=3).
  // raypath {5, 7, 3}: first_pri = 5 (from face 5). face 5 → 3, face 7 → 5, face 3 → 7.
  // So {5,7,3} should reduce to same orbit canonical as {3,5,7}? Only if under P symmetry
  // they are in the same orbit (yes, they are P-rotations of each other when seed is rotated).
  // Wait, {5,7,3} P-shift by -2 gives {3,5,1}? Let me verify with orbit invariant test.
  Crystal prism = Crystal::CreatePrism(1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymP, 0, false, { 3, 5, 7 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymP, 0, false, { 5, 7, 3 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymP, 0, false, { 7, 3, 5 }));
  // These three should reduce to the SAME canonical (they're in the same P-orbit).
  auto c1 = prism.ReduceRaypath({ 3, 5, 7 }, FilterConfig::kSymP, 0, false, true, true);
  auto c2 = prism.ReduceRaypath({ 5, 7, 3 }, FilterConfig::kSymP, 0, false, true, true);
  auto c3 = prism.ReduceRaypath({ 7, 3, 5 }, FilterConfig::kSymP, 0, false, true, true);
  // Wait — {3,5,7}, {5,7,3}, {7,3,5} are different sequences (segment ORDER matters).
  // P-shift on {3,5,7} by k gives {3+k, 5+k, 7+k} mod 6 (with +3 offset). So {3,5,7} and
  // {5,7,3} are P-related: shift by 2 gives {5,7,9 mod 6 + 3} = {5,7,3}. Yes!
  EXPECT_EQ(c1, c2);
  EXPECT_EQ(c1, c3);
}

// ============================================================================
// H6: low-symmetry shapes
// ============================================================================
// Oracle, independent of DeriveGeometricSymmetry and of the face_distance bookkeeping: a candidate
// symmetry element is a permutation of the prism-face index (a rotation i -> i+k or a mirror
// i -> a-i) optionally combined with B (basal 1<->2, cone 1x<->2x). It is a symmetry of the crystal
// iff the matching rigid motion — a rotation or vertical reflection about the c-axis that carries
// face 3's normal onto its image's, plus z -> -z for B — carries EVERY built face plane (normal and
// offset, as Crystal::GetPolygonFaceNormal/Dist report them) onto the plane of the face the element
// names. The allowed group is the closure of the requested generators that pass this test (D: only
// sigma_a, and only when d_applicable). Two raypaths must reduce to the same canonical form iff one
// is in the other's orbit under that group.

namespace {

struct SymElem {
  int perm[6];
  bool b;
  bool mirror;
};

SymElem Rot(int k, bool b) {
  SymElem e{};
  for (int i = 0; i < 6; i++) {
    e.perm[i] = (i + k) % 6;
  }
  e.b = b;
  e.mirror = false;
  return e;
}

SymElem Mir(int a, bool b) {
  SymElem e{};
  for (int i = 0; i < 6; i++) {
    e.perm[i] = ((a - i) % 6 + 6) % 6;
  }
  e.b = b;
  e.mirror = true;
  return e;
}

SymElem Compose(const SymElem& g, const SymElem& h) {  // g after h
  SymElem e{};
  for (int i = 0; i < 6; i++) {
    e.perm[i] = g.perm[h.perm[i]];
  }
  e.b = g.b != h.b;
  e.mirror = g.mirror != h.mirror;
  return e;
}

bool SameElem(const SymElem& a, const SymElem& b) {
  return a.b == b.b && std::equal(a.perm, a.perm + 6, b.perm);
}

IdType ApplyToFace(const SymElem& e, IdType x) {
  if (x <= 2) {
    return e.b ? static_cast<IdType>(3 - x) : x;
  }
  int pyr = x / 10;
  int pri = x % 10 - 3;
  if (e.b && pyr == 1) {
    pyr = 2;
  } else if (e.b && pyr == 2) {
    pyr = 1;
  }
  return static_cast<IdType>(pyr * 10 + e.perm[pri] + 3);
}

std::vector<IdType> Apply(const SymElem& e, const std::vector<IdType>& rp) {
  std::vector<IdType> out;
  out.reserve(rp.size());
  for (auto x : rp) {
    out.push_back(ApplyToFace(e, x));
  }
  return out;
}

std::vector<SymElem> AllHexElems() {
  std::vector<SymElem> all;
  for (int b = 0; b < 2; b++) {
    for (int k = 0; k < 6; k++) {
      all.push_back(Rot(k, b != 0));
      all.push_back(Mir(k, b != 0));
    }
  }
  return all;
}

// Does the rigid motion behind `e` carry the built crystal onto itself, face for face?
bool IsPhysicalSymmetry(const Crystal& c, const SymElem& e) {
  struct Plane {
    float n[3];
    float d;
  };
  std::vector<std::pair<IdType, Plane>> planes;
  const float* n = c.GetPolygonFaceNormal();
  const float* d = c.GetPolygonFaceDist();
  for (size_t p = 0; p < c.PolygonFaceCount(); p++) {
    planes.push_back({ c.GetFn(static_cast<IdType>(p)), Plane{ { n[p * 3], n[p * 3 + 1], n[p * 3 + 2] }, d[p] } });
  }
  auto find = [&planes](IdType fn) -> const Plane* {
    for (const auto& [f, pl] : planes) {
      if (f == fn) {
        return &pl;
      }
    }
    return nullptr;
  };
  const Plane* f3 = find(3);
  const Plane* f3_img = find(ApplyToFace(e, 3));
  if (f3 == nullptr || f3_img == nullptr) {
    return false;
  }
  const double t0 = std::atan2(f3->n[1], f3->n[0]);
  const double t1 = std::atan2(f3_img->n[1], f3_img->n[0]);
  for (const auto& [f, pl] : planes) {
    const Plane* img = find(ApplyToFace(e, f));
    if (img == nullptr) {
      return false;
    }
    const double t = std::atan2(pl.n[1], pl.n[0]);
    const double r = std::hypot(pl.n[0], pl.n[1]);
    const double t_new = e.mirror ? (t0 + t1) - t : t + (t1 - t0);
    const double nx = r * std::cos(t_new);
    const double ny = r * std::sin(t_new);
    const double nz = e.b ? -pl.n[2] : pl.n[2];
    const double err = std::fabs(nx - img->n[0]) + std::fabs(ny - img->n[1]) + std::fabs(nz - img->n[2]) +
                       std::fabs(static_cast<double>(pl.d) - img->d);
    if (err > 1e-4) {
      return false;
    }
  }
  return true;
}

// Closure of the requested generators the crystal's shape passes.
std::vector<SymElem> AllowedGroup(const Crystal& c, uint8_t symmetry, int sigma_a, bool d_applicable) {
  std::vector<SymElem> gens;
  if (symmetry & FilterConfig::kSymP) {
    for (int k = 1; k < 6; k++) {
      if (IsPhysicalSymmetry(c, Rot(k, false))) {
        gens.push_back(Rot(k, false));
      }
    }
  }
  if ((symmetry & FilterConfig::kSymD) && d_applicable && IsPhysicalSymmetry(c, Mir(sigma_a, false))) {
    gens.push_back(Mir(sigma_a, false));
  }
  if ((symmetry & FilterConfig::kSymB) && IsPhysicalSymmetry(c, Rot(0, true))) {
    gens.push_back(Rot(0, true));
  }
  std::vector<SymElem> group{ Rot(0, false) };
  for (size_t i = 0; i < group.size(); i++) {
    for (const auto& g : gens) {
      SymElem h = Compose(g, group[i]);
      if (std::none_of(group.begin(), group.end(), [&h](const SymElem& x) { return SameElem(x, h); })) {
        group.push_back(h);
      }
    }
  }
  return group;
}

// Every raypath and every one of its 24 hexagonal images: same canonical form iff the image is in the
// allowed orbit; and ExpandRaypath enumerates exactly that orbit.
::testing::AssertionResult VerifyAgainstShapeOracle(const Crystal& c, const std::vector<IdType>& faces, uint32_t seed) {
  std::mt19937 rng(seed);
  std::uniform_int_distribution<size_t> face_pick(0, faces.size() - 1);
  std::uniform_int_distribution<int> len_pick(1, 4);
  const auto all = AllHexElems();
  for (uint8_t sym = 1; sym <= 7; sym++) {
    for (int sigma_a = 0; sigma_a < 6; sigma_a++) {
      for (bool d_applicable : { true, false }) {
        const auto group = AllowedGroup(c, sym, sigma_a, d_applicable);
        for (int n = 0; n < 20; n++) {
          std::vector<IdType> rp(static_cast<size_t>(len_pick(rng)));
          for (auto& x : rp) {
            x = faces[face_pick(rng)];
          }
          std::set<std::vector<IdType>> orbit;
          for (const auto& g : group) {
            orbit.insert(Apply(g, rp));
          }
          const auto expanded = c.ExpandRaypath(rp, sym, sigma_a, d_applicable, true, true);
          const std::set<std::vector<IdType>> expanded_set(expanded.begin(), expanded.end());
          if (expanded_set != orbit) {
            return ::testing::AssertionFailure()
                   << "ExpandRaypath orbit of " << FormatRaypath(rp) << " has " << expanded_set.size()
                   << " members, shape oracle " << orbit.size() << " (sym=" << int{ sym } << " sigma_a=" << sigma_a
                   << " d_applicable=" << d_applicable << ")";
          }
          const auto canon = c.ReduceRaypath(rp, sym, sigma_a, d_applicable, true, true);
          for (const auto& g : all) {
            const auto img = Apply(g, rp);
            const bool same = c.ReduceRaypath(img, sym, sigma_a, d_applicable, true, true) == canon;
            const bool equivalent = orbit.count(img) > 0;
            if (same != equivalent) {
              return ::testing::AssertionFailure()
                     << FormatRaypath(rp) << " and " << FormatRaypath(img) << (same ? " merged" : " split")
                     << " but the shape oracle says " << (equivalent ? "equivalent" : "inequivalent")
                     << " (sym=" << int{ sym } << " sigma_a=" << sigma_a << " d_applicable=" << d_applicable << ")";
            }
          }
        }
      }
    }
  }
  return ::testing::AssertionSuccess();
}

const std::vector<IdType> kPrismFaces{ 1, 2, 3, 4, 5, 6, 7, 8 };
const std::vector<IdType> kPyramidFaces{ 1, 2, 3, 4, 5, 6, 7, 8, 13, 14, 15, 16, 17, 18, 23, 24, 25, 26, 27, 28 };

// DeriveGeometricSymmetry's three fields, read against the same physical test.
::testing::AssertionResult VerifyDerivedFields(const Crystal& c) {
  const auto& g = c.GeomSymmetry();
  int p_step = 6;
  for (int k : { 1, 2, 3 }) {
    if (IsPhysicalSymmetry(c, Rot(k, false))) {
      p_step = k;
      break;
    }
  }
  uint8_t mask = 0;
  for (int a = 0; a < 6; a++) {
    if (IsPhysicalSymmetry(c, Mir(a, false))) {
      mask = static_cast<uint8_t>(mask | (1u << a));
    }
  }
  const bool b = IsPhysicalSymmetry(c, Rot(0, true));
  if (g.p_step != p_step || g.d_valid_sigma_mask != mask || g.b_applicable != b) {
    return ::testing::AssertionFailure() << "derived {p_step=" << g.p_step << " mask=" << int{ g.d_valid_sigma_mask }
                                         << " b=" << g.b_applicable << "} vs shape {p_step=" << p_step
                                         << " mask=" << int{ mask } << " b=" << b << "}";
  }
  return ::testing::AssertionSuccess();
}

}  // namespace

TEST(H6_LowSymmetryShape_Audit, BacklogReproPrismKeepsTheTwoEnergyBucketsApart) {
  // face_distance [1, 1.2, 1, 1.2, 1, 1.2]: a three-fold axis, not six-fold. {3,5} (near faces) and
  // {4,6} (far faces) are a 60° rotation apart and must NOT be merged by P; {5,7} is 120° away and must.
  const float dist[6]{ 1.0f, 1.2f, 1.0f, 1.2f, 1.0f, 1.2f };
  const Crystal c = Crystal::CreatePrism(1.0f, dist);
  ASSERT_EQ(c.FnPeriod(), 6);  // the face-number modulus is unchanged
  EXPECT_EQ(c.GeomSymmetry().p_step, 2);
  const auto canon = c.ReduceRaypath({ 3, 5 }, FilterConfig::kSymP);
  EXPECT_NE(c.ReduceRaypath({ 4, 6 }, FilterConfig::kSymP), canon);
  EXPECT_EQ(c.ReduceRaypath({ 5, 7 }, FilterConfig::kSymP), canon);
  EXPECT_EQ(c.ReduceRaypath({ 7, 3 }, FilterConfig::kSymP), canon);
  // D with an odd sigma_a would swap near and far faces too (sigma_1 sends {3,4} to {4,3}); with an
  // even one it is a real mirror of this shape (sigma_0 sends {3,4} to {3,8}).
  EXPECT_NE(c.ReduceRaypath({ 3, 4 }, FilterConfig::kSymD, 1, true, true, true),
            c.ReduceRaypath({ 4, 3 }, FilterConfig::kSymD, 1, true, true, true));
  EXPECT_EQ(c.ReduceRaypath({ 3, 4 }, FilterConfig::kSymD, 0, true, true, true),
            c.ReduceRaypath({ 3, 8 }, FilterConfig::kSymD, 0, true, true, true));
  EXPECT_TRUE(VerifyDerivedFields(c));
}

TEST(H6_LowSymmetryShape_Audit, RegularPrismAndSymmetricPyramidStayFullyHexagonal) {
  EXPECT_EQ(Crystal::CreatePrism(1.3f).GeomSymmetry(), kFullHexagonalSymmetry);
  EXPECT_EQ(Crystal::CreatePyramid(1.0f, 1.0f, 1.0f).GeomSymmetry(), kFullHexagonalSymmetry);
  EXPECT_EQ(Crystal::CreatePyramid(28.0f, 28.0f, 0.4f, 1.0f, 0.4f).GeomSymmetry(), kFullHexagonalSymmetry);
}

TEST(H6_LowSymmetryShape_Audit, PrismShapesAgainstTheFacePlaneOracle) {
  const float kDists[][6] = {
    { 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f },  // six-fold, all mirrors
    { 1.0f, 1.2f, 1.0f, 1.2f, 1.0f, 1.2f },  // three-fold (p_step 2), even mirrors
    { 1.0f, 1.0f, 1.3f, 1.0f, 1.0f, 1.3f },  // two-fold (p_step 3)
    { 1.0f, 1.2f, 1.3f, 1.3f, 1.2f, 1.0f },  // one mirror only (sigma_a = 5)
    { 1.0f, 1.1f, 1.2f, 1.3f, 1.4f, 1.5f },  // nothing but B
  };
  for (const auto& dist : kDists) {
    const Crystal c = Crystal::CreatePrism(0.8f, dist);
    SCOPED_TRACE("dist = {" + std::to_string(dist[0]) + ", " + std::to_string(dist[1]) + ", " +
                 std::to_string(dist[2]) + ", " + std::to_string(dist[3]) + ", " + std::to_string(dist[4]) + ", " +
                 std::to_string(dist[5]) + "}");
    EXPECT_TRUE(VerifyDerivedFields(c));
    EXPECT_TRUE(VerifyAgainstShapeOracle(c, kPrismFaces, 20260927u));
  }
}

TEST(H6_LowSymmetryShape_Audit, PyramidShapesAgainstTheFacePlaneOracle) {
  const float kRegular[6]{ 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f };
  const float kThreeFold[6]{ 1.0f, 1.2f, 1.0f, 1.2f, 1.0f, 1.2f };
  struct Case {
    const char* what;
    float alpha_u, alpha_l, h1, h2, h3;
    const float* dist;
    bool expect_b;
  };
  const Case kCases[] = {
    { "symmetric cones, three-fold section", 28.0f, 28.0f, 0.4f, 1.0f, 0.4f, kThreeFold, true },
    { "unequal wedge angles", 28.0f, 40.0f, 0.4f, 1.0f, 0.4f, kRegular, false },
    { "unequal cone heights", 28.0f, 28.0f, 0.3f, 1.0f, 0.6f, kRegular, false },
    { "upper cone only", 28.0f, 28.0f, 0.4f, 1.0f, 0.0f, kRegular, false },
  };
  for (const auto& k : kCases) {
    SCOPED_TRACE(k.what);
    const Crystal c = Crystal::CreatePyramid(k.alpha_u, k.alpha_l, k.h1, k.h2, k.h3, k.dist);
    if (c.PolygonFaceCount() == 0) {
      ADD_FAILURE() << "degenerate crystal: the case exercises nothing";
      continue;
    }
    EXPECT_EQ(c.GeomSymmetry().b_applicable, k.expect_b);
    EXPECT_TRUE(VerifyDerivedFields(c));
    EXPECT_TRUE(VerifyAgainstShapeOracle(c, kPyramidFaces, 20260928u));
  }
}

}  // namespace lumice
